# Generated by Django 2.2.6 on 2019-11-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_access', models.DateField()),
                ('last_access', models.DateField()),
                ('default_min_votes_threshold', models.FloatField(default=0.03)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_votes_threshold', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Device')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ElectionType')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('registered_voters', models.PositiveIntegerField()),
                ('num_representatives', models.PositiveIntegerField()),
                ('blank_votes', models.PositiveIntegerField()),
                ('void_votes', models.PositiveIntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrv_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('votes', models.PositiveIntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.District')),
            ],
        ),
    ]
