# Generated by Django 2.2.6 on 2019-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default_min_votes_threshold',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='votes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='blank_votes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='num_representatives',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='registered_voters',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='void_votes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='min_votes_threshold',
            field=models.FloatField(),
        ),
    ]
