# Generated by Django 2.2.6 on 2019-11-23 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191123_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='abrv_name',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Candidature's abvr_name format error", regex='^([a-z]|[A-Z]){1}(\\w){0,5}$')]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message="Candidature's name format error", regex='^([a-z]|[A-Z]){1}(\\w){0,69}$')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='default_min_votes_threshold',
            field=models.FloatField(default=0.03, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=100.0)]),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message="District's name format error", regex='^([a-z]|[A-Z]){1,120}$')]),
        ),
        migrations.AlterField(
            model_name='election',
            name='min_votes_threshold',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=100.0)]),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="ElectionType's name can contain only alphabetic characters", regex='^([a-z]|[A-Z]){1,20}$')]),
        ),
    ]
